Feat: Improve Debian test check

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -54,7 +54,13 @@ jobs:
                   sed -i 's/<tenant_id>/${{ secrets.TENANT_ID }}/' aic.yml
                   sed -i 's/<client_secret>/${{ secrets.CLIENT_SECRET }}/' aic.yml
                   sed -i 's/# - LinuxDebian12/- LinuxDebian12/' aic.yml
-                  python main.py && exit 1 || exit 0
+                  OUTPUT=$(python main.py)
+                  echo $OUTPUT
+                  if echo "$OUTPUT" | grep -q "Jenkins pipeline failed. This is not an AIC error."; then
+                    exit 0
+                  else
+                    exit 1
+                  fi
 
             - name: Run AIC on Windows Server 2022
               run: |
